@startuml
actor User
actor Admin

(Play new game) as (UC1)
(Save game) as (UC2)
(Load game) as (UC3)
(Show high scores) as (UC4)
(Reset high scores) as (UC5)

User --> UC1
User --> UC2
User --> UC3
User --> UC4
Admin --> UC5
@enduml
